"""Removed Role table

Revision ID: 32f60ef6c769
Revises: 935fac35532f
Create Date: 2018-07-23 07:38:49.045636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f60ef6c769'
down_revision = '935fac35532f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_template_id', table_name='role')
    op.drop_table('role')
    op.drop_index('ix_party_role', table_name='party')
    op.drop_constraint(None, 'party', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'party', 'role', ['role'], ['id'])
    op.create_index('ix_party_role', 'party', ['role'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_template_id', 'role', ['template_id'], unique=False)
    # ### end Alembic commands ###
