"""role, contract and party

Revision ID: 4ee5de61ddd3
Revises: ae5ae91a9710
Create Date: 2018-07-21 13:38:58.596688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee5de61ddd3'
down_revision = 'ae5ae91a9710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.TEXT(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_owner_id'), 'contract', ['owner_id'], unique=False)
    op.create_index(op.f('ix_contract_status'), 'contract', ['status'], unique=False)
    op.create_index(op.f('ix_contract_template_id'), 'contract', ['template_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_template_id'), 'role', ['template_id'], unique=False)
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('signed_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_contract_id'), 'party', ['contract_id'], unique=False)
    op.create_index(op.f('ix_party_party_id'), 'party', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_role'), 'party', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_party_role'), table_name='party')
    op.drop_index(op.f('ix_party_party_id'), table_name='party')
    op.drop_index(op.f('ix_party_contract_id'), table_name='party')
    op.drop_table('party')
    op.drop_index(op.f('ix_role_template_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_contract_template_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_status'), table_name='contract')
    op.drop_index(op.f('ix_contract_owner_id'), table_name='contract')
    op.drop_table('contract')
    # ### end Alembic commands ###
