"""Added party labels and params to template

Revision ID: 935fac35532f
Revises: 4ee5de61ddd3
Create Date: 2018-07-23 06:43:20.832801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935fac35532f'
down_revision = '4ee5de61ddd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('params', sa.TEXT(), nullable=True))
    op.add_column('template', sa.Column('party_labels', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'party_labels')
    op.drop_column('template', 'params')
    # ### end Alembic commands ###
