"""contract templates table

Revision ID: a5d3c0b30a9e
Revises: 6b65be4388cd
Create Date: 2018-07-21 09:52:50.631850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d3c0b30a9e'
down_revision = '6b65be4388cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_owner_id'), 'template', ['owner_id'], unique=False)
    op.create_index(op.f('ix_template_title'), 'template', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_title'), table_name='template')
    op.drop_index(op.f('ix_template_owner_id'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
