"""Contract parent

Revision ID: be8f40ab09a9
Revises: fb7319b0edb5
Create Date: 2018-08-07 04:36:40.510124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8f40ab09a9'
down_revision = 'fb7319b0edb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contract_parent_id'), 'contract', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'contract', 'contract', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_index(op.f('ix_contract_parent_id'), table_name='contract')
    op.drop_column('contract', 'parent_id')
    # ### end Alembic commands ###
